%YAML:1.0
---
AnnotationsSet:
   Configuration:
      ImageFilesNamingRule: "%OrImPa%annotations/%OrImFiNa%_annotsBB/%FrNu%.png"
      SummaryFileNamingRule: "%OrImPa%annotations/%OrImFiNa%_annotsBB/summary.yaml"
      ClassesDefinitions:
         - { Name:Road, Type:0, DispColRGB:[ 85, 85, 85 ],
             IdRecRangeMinBGR:[ 127, 127, 0 ], IdRecRangeMaxBGR:[ 0, 0,
             0 ] }
         - { Name:Car, Type:2, DispColRGB:[ 255, 0, 0 ],
             IdRecRangeMinBGR:[ 0, 0, 127 ], IdRecRangeMaxBGR:[ 255, 255,
             255 ] }
         - { Name:Truck, Type:2, DispColRGB:[ 0, 127, 0 ],
             IdRecRangeMinBGR:[ 0, 0, 85 ], IdRecRangeMaxBGR:[ 255, 255,
             100 ] }
         - { Name:Utility, Type:2, DispColRGB:[ 0, 0, 255 ],
             IdRecRangeMinBGR:[ 0, 0, 50 ], IdRecRangeMaxBGR:[ 255, 255,
             84 ] }
